[profile.ci.fuzz]
runs = 10_000

[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]
solc_version = "0.8.26"
evm_version = "cancun"
viaIR = true